#name: Test
#
#on: [ push, pull_request ]
#
#jobs:
#  test:
#    strategy:
#      fail-fast: false
#      matrix:
#        include:
#          - os: macos-latest
#            arch: amd64
#          - os: ubuntu-latest
#    runs-on: ${{ matrix.os }}
#    steps:
#      - name: Check out Git repository
#        uses: actions/checkout@main
#
#      # 安装jre Windows
#      - name: Install Jre for Windows
#        uses: actions/setup-java@main
#        with:
#          java-version: "17"
#          distribution: "temurin"
#          java-package: "jre"
#
#      # java.security 开放tls1 Linux
#      - name: Enable tls1
#        run: |
#          ls ${{ env.JAVA_HOME }}
#          ls ${{ env.JAVA_HOME }}/legal/jdk.zipfs/
#          cat ${{ env.JAVA_HOME }}/legal/jdk.zipfs/ADDITIONAL_LICENSE_INFO